# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - feature/*
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  Version: 0.1.0
  VersionSuffix: alpha1
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  Configuration: Release

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: |
      $height = git rev-list --count HEAD
      $env:VersionSuffix = if($env:VersionSuffix){
      "-${env:VersionSuffix}.${height}"
      } else {
        "+${height}"
      }
      Write-Output "##vso[build.updatebuildnumber]$env:Version$env:VersionSuffix"
      Write-Output "##vso[task.setvariable variable=VersionSuffix;]$env:VersionSuffix"
    displayName: "PowerShell: Calculate Height"
  - powershell: .\build.ps1
    displayName: "PowerShell: build.ps1"