# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - feature/*
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  Version: 0.1.0
  VersionSuffix: alpha1
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  Configuration: Release

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  # PR branches should include the pr label part
  - powershell: |
      if($env:BUILD_SOURCEBRANCH -match 'refs\/pull\/(?<id>\d+)\/merge'){
          $env:VersionSuffix += ".pr$($matches.id)"
          Write-Output "##vso[task.setvariable variable=VersionSuffix;]$env:VersionSuffix"
      }
    displayName: "PowerShell: Update build label"

  # Calculate the height - this will be reafactored in the future
  - powershell: |
      $height = git rev-list --count HEAD
      $env:VersionSuffix = if($env:VersionSuffix){
      "-${env:VersionSuffix}.${height}"
      } else {
        "+${height}"
      }
      Write-Output "##vso[build.updatebuildnumber]$env:Version$env:VersionSuffix"
      Write-Output "##vso[task.setvariable variable=VersionSuffix;]$env:VersionSuffix"
    displayName: "PowerShell: Calculate Height"

  # Run the actual build script
  - powershell: .\build.ps1
    displayName: "PowerShell: build.ps1"

  # Handle artifacts
  - task: CopyFiles@1
    inputs:
      sourceFolder: .\artifacts
      Contents: |
        **\*.zip
      TargetFolder: $(Build.ArtifactStagingDirectory)/distributables
    displayName: "Artifacts: Collect distributables"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/distributables
      ArtifactName: distributables
      ArtifactType: Container
    displayName: "Artifacts: Publish distributables"
    condition: and(succeeded(), ne(variables['system.pullrequest.isfork'], true))