# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  Version: 0.1.0
  VersionSuffix: alpha1
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  Configuration: Release
  DistDir: $(Build.ArtifactStagingDirectory)/distributables

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  # Calculate the version suffix - this will be refactored in the future
  - powershell: |
      $height = git rev-list --count HEAD
      if($env:BUILD_SOURCEBRANCH -match 'refs\/pull\/(?<id>\d+)\/merge'){
          if($env:VersionSuffix){
              $env:VersionSuffix += ".pr$($matches.id)"
          } else {
              $env:VersionSuffix = ".pr$($matches.id)"
          }
      }
      $env:VersionSuffix = if($env:VersionSuffix){
        "${env:VersionSuffix}.${height}"
      } else {
        "+${height}"
      }
      Write-Output "##vso[build.updatebuildnumber]$env:Version $env:VersionSuffix"
      Write-Output "##vso[task.setvariable variable=VersionSuffix;]$env:VersionSuffix"
    displayName: "Build: Calculate Height"

  # Build/Pack the assets
  - task: DotNetCoreCLI@2
    displayName: "Build: Pack Source"
    inputs:
      command: pack
      packagesToPack: src/**/*.csproj
      packDirectory: $(DistDir)
      versioningScheme: off

  # Run unit tests
  - task: DotNetCoreCLI@2
    displayName: "Test: Unit"
    inputs:
      command: test
      projects: test/**/*.csproj
      publishTestResults: true

  # Run integration tests
  - powershell: |
      .\integration\test.ps1 -Artifacts $(DistDir)
    displayName: "Test: Integration"
    failOnStderr: true
     
  - task: PublishTestResults@2
    displayName: "Artifacts: Publish Integration Tests"
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/*.Pester.xml' 
      searchFolder: $(DistDir)\.. 
      testRunTitle: "Integration Tests"

  # Handle artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Artifacts: Publish Distributables"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      PathtoPublish: $(DistDir)
      ArtifactName: distributables
      ArtifactType: Container
    
  - task: NuGetCommand@2
    displayName: "Artifacts: Publish Packages"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))   
    inputs:
      command: push
      packagesToPush: $(DistDir)/**/*.nupkg
      nuGetFeedType: internal
      publishVstsFeed: SimpleVersion
      feedsToUse: nuget.config