# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - feature/*
    - master
    - azure-pipelines
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU


jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: .\build.ps1
    displayName: "build.ps1"