# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*
    - .github/*
    - README.md

pr:
- master
- release/*

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  Configuration: Release
  ArtifactsPath: $(Build.ArtifactStagingDirectory)

jobs:
- job: 'Build_Assets'
  pool:
    vmImage: windows-latest
  steps:

  # Build
  - pwsh: ./build.ps1 -BuildDocs -ArtifactsPath $(ArtifactsPath) -Configuration $(Configuration)
    displayName: 'Build and Test'

  # Publish test results
  - task: PublishTestResults@2
    displayName: 'Tests: Publish unit tests'
    condition: succeededOrFailed()
    inputs:
      testRunTitle: Unit Tests
      testRunner: vstest
      testResultsFiles: '$(ArtifactsPath)/**/*.trx'

  # Publish coverage
  - task: PublishCodeCoverageResults@1
    displayName: "Tests: Publish unit test coverage"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(ArtifactsPath)/**/*.cobertura.xml'
      reportDirectory: '$(ArtifactsPath)/coveragereport'

  # Quality check the build
  - task: BuildQualityChecks@6
    displayName: 'Checks: Quality'
    inputs:
      checkWarnings: true
      warningFailOption: 'fixed'
      warningThreshold: '0'
      evaluateTaskWarnings: false
      checkCoverage: true
      coverageFailOption: 'fixed'
      coverageType: 'branches'
      coverageThreshold: '90'

  # Handle artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Artifacts: Publish"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      PathtoPublish: $(ArtifactsPath)
      ArtifactName: Artifacts
      ArtifactType: Container

  - task: NuGetCommand@2
    displayName: "Artifacts: Push Packages"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      command: push
      packagesToPush: $(ArtifactsPath)/**/*.nupkg
      nuGetFeedType: internal
      publishVstsFeed: SimpleVersion
      feedsToUse: nuget.config
