# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  Configuration: Release
  DistDir: $(Build.ArtifactStagingDirectory)/distributables
  LocalFeed: https://pkgs.dev.azure.com/Kieranties/_packaging/SimpleVersion/nuget/v3/index.json

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:

  # Install nuget
  - task: NuGetToolInstaller@0
    displayName: 'Prepare: Install NuGet'

  # Install previous release
  - task: NuGetCommand@2
    displayName: 'Prepare: Install SimpleVersion'
    inputs:
      command: custom
      arguments: 'install SimpleVersion.Command -Pre -Source $(LocalFeed)'

  # Calculate the version
  - powershell: |
      # We need to be checked out on a branch - Ideally this would be handled in SimpleVersion itself
      # Get the full branch and remove the refs/heads
      $branchName = '$(Build.SourceBranch)' -replace '^refs/heads/',''
      git checkout --progress --force $branchName
      $result = .\SimpleVersion.*\tools\SimpleVersion.exe
      Write-Output $result
      $fullVersion = ($result | ConvertFrom-Json).Formats.Semver2
      Write-Output "##vso[build.updatebuildnumber]$fullVersion"
      if($fullVersion -match '(?<version>\d+\.\d+\.\d+(?:\.\d+)?)-?(?<suffix>.*)') {
        Write-Output "##vso[task.setvariable variable=Version;]$($Matches.version)"
        Write-Output "##vso[task.setvariable variable=VersionSuffix;]$($Matches.suffix)"
      }
    displayName: 'Prepare: Set version information'

  # Build/Pack the assets
  - task: DotNetCoreCLI@2
    displayName: "Build: Pack Source"
    inputs:
      command: pack
      packagesToPack: src/**/*.csproj
      packDirectory: $(DistDir)
      versioningScheme: off

  # Run unit tests
  - task: DotNetCoreCLI@2
    displayName: "Test: Unit"
    inputs:
      command: test
      projects: test/**/*.csproj
      publishTestResults: true

  # TODO - Renable integration tests. Currently fail as environment variables
  # are always collected, so branch always maps to current repo branch being built

  # Run integration tests
  #- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  #  displayName: "Test: Integration"
  #  inputs:
  #    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\integration\*.Command.Tests.ps1''; Parameters=@{ Artifacts=''$(Build.ArtifactStagingDirectory)/distributables''}}'
  #    resultsFile: '$(Build.ArtifactStagingDirectory)\Pester.Tests.XML'

  # Publish integration tests
  #- task: PublishTestResults@2
  #  displayName: "Artifacts: Publish Integration Tests"
  #  condition: succeededOrFailed()
  #  inputs:
  #    testResultsFormat: NUnit
  #    testResultsFiles: $(Build.ArtifactStagingDirectory)\Pester.Tests.xml
  #    testRunTitle: "Integration Tests"

  # Handle artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Artifacts: Publish Distributables"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      PathtoPublish: $(DistDir)
      ArtifactName: distributables
      ArtifactType: Container

  - task: NuGetCommand@2
    displayName: "Artifacts: Publish Packages"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      command: push
      packagesToPush: $(DistDir)/**/*.nupkg
      nuGetFeedType: internal
      publishVstsFeed: SimpleVersion
      feedsToUse: nuget.config
