# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - feature/*
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: .\build.ps1
    displayName: "PowerShell: build.ps1"