# Build pipeline for Azure Devops
trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*
    - .github/*
    - README.md

pr:
- master
- release/*

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  Configuration: Release
  ArtifactsDir: $(Build.ArtifactStagingDirectory)

jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:

  # Build
  - powershell: ./build.ps1 -BuildDocs -ArtifactsPath $(ArtifactsDir) -Configuration $(Configuration)
    displayName: 'Build'

  # Publish test results
  - task: PublishTestResults@2
    displayName: 'Tests: Publish unit tests'
    continueOnError: true
    inputs:
      testRunTitle: Unit Tests
      testRunner: vstest
      testResultsFiles: '$(ArtifactsDir)/**/*.trx'

  # Publish coverage
  - task: PublishCodeCoverageResults@1
    displayName: "Tests: Publish unit test coverage"
    continueOnError: true
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(ArtifactsDir)/**/*.cobertura.xml'

  # Quality check the build
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
    displayName: 'Checks: Quality'
    inputs:
      checkWarnings: true
      showStatistics: true
      checkCoverage: true
      coverageFailOption: fixed
      coverageThreshold: 90
      coverageType: branches

  # Handle artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Artifacts: Publish"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      PathtoPublish: $(ArtifactsDir)
      ArtifactName: Artifacts
      ArtifactType: Container

  - task: NuGetCommand@2
    displayName: "Artifacts: Push Packages"
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      command: push
      packagesToPush: $(ArtifactsDir)/**/*.nupkg
      nuGetFeedType: internal
      publishVstsFeed: SimpleVersion
      feedsToUse: nuget.config
